Added tests for the initial code
BastienVienet/epsic-tdd-labo2-rust pull request #1
Opened 2024-01-11 08:24 UTC by Myrly

Added tests for add and substract method for the initial code, not part of the tdd development yet.

2024-01-11 16:55 UTC, BastienVienet requested changes

2024-01-11 16:55 UTC, BastienVienet commented on src/main.rs
> +
Possibilité de mettre le tout dans plusieurs autres fichiers ?
1 fichier pour addition, 1 autre pour la soustraction.

2024-01-12 09:47 UTC, Myrly commented on src/main.rs
> +
C'est une convention de Rust de mettre les tests au bas du fichier où se trouvent les fonctions qu'ils testent, donc ça reste là 🫵 😂

2024-01-12 09:53 UTC, BastienVienet approved these changes

2024-01-12 09:54 UTC, merged